server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_db
    username: postgres
    password: 18445671
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  cache:
    type: simple

logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-history: 30
      file-name-pattern: logs/app.%d{yyyy-MM-dd}.log
  level:
    root: INFO

